set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_EXTENSIONS NO)
set(CMAKE_EXPORT_COMPILE_COMMANDS YES)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
set(CMAKE_COLOR_DIAGNOSTICS YES)
if(WIN32)
  add_compile_definitions(WIN32=1)
endif()
include(FetchContent)
FetchContent_Declare(
  pegtl
  GIT_REPOSITORY https://github.com/taocpp/pegtl.git
  GIT_TAG 3.2.8
  GIT_SHALLOW ON
  SYSTEM EXCLUDE_FROM_ALL OVERRIDE_FIND_PACKAGE)
FetchContent_Declare(
  ftxui
  GIT_REPOSITORY https://github.com/ArthurSonzogni/FTXUI.git
  GIT_TAG main
  GIT_SHALLOW ON
  SYSTEM EXCLUDE_FROM_ALL OVERRIDE_FIND_PACKAGE)
